# Generated by Django 5.1.4 on 2024-12-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_alter_topico_data_comunicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunicado',
            old_name='f',
            new_name='topico',
        ),
    ]
