# Generated by Django 5.1.4 on 2024-12-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_rename_f_comunicado_topico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
