# Generated by Django 5.1.4 on 2024-12-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_alter_comunicado_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
