# Generated by Django 5.1.4 on 2024-12-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacoes',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transacoes',
            name='opcional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
